<?php
/**
 * @var int $width
 * @var int $height
 * @var bool $enableRatioLabel
 * @var bool $enableRaw
 * @var string $chartId
 * @var string $valueSuffix
 * @var Tlapnet\Chart\Segment\PieSegment[] $segments
 * @var Tlapnet\Chart\PieChart[] $raw
 */
?>
<div id="<?php echo $chartId ?>" style="width: <?php echo $width ?>; height: <?php echo $height ?>;">
	<?php if (!$segments): ?>
		<div class="empty-chart-warning">
			Nedostatek dat k realizaci grafu.
		</div>
	<?php endif ?>
</div>
<?php //dump($raw) ?>

<?php if ($segments): ?>
	<script type="text/javascript">
		(function() {
			'use strict';

			var data = {
				type : 'pie',
				columns: []
			};

			var pie = {
				label: {}
			};

			<?php if (!$enableRatioLabel): ?>
				pie.label.format = function (value, ratio, id) {
					return value + '<?php echo $valueSuffix ?>';
				};
			<?php endif ?>

			<?php $i = 0 ?>
			<?php if (!$enableRaw): ?>
				<?php foreach ($segments as $segment): ?>
					<?php $i++ ?>

					var column = [
						'<?php echo $segment->getTitle() ?>',
						<?php echo $segment->getValue() ?>
					];

					data.columns.push(column);
				<?php endforeach ?>
			<?php else :?>
				data.columns = <?php echo json_encode($raw) ?>;
			<?php endif ?>
			//console.log(data.columns);

			var chart = c3.generate({
				bindto: '#<?php echo $chartId ?>',
				data: data,
				pie: pie
			});
			$('#<?php echo $chartId ?>').data('c3-chart', chart);
		})();
	</script>
<?php endif ?>
